# OIDC Gateway - Development Configuration
# This configuration is optimized for local development

server:
  port: 8080
  host: "0.0.0.0"

oidc:
  provider_url: "http://localhost:8081/auth/realms/compas"
  client_id: "compas-auth-proxy"
  client_secret: "dev-secret"
  redirect_url: "http://localhost:8080/auth/callback"
  scopes: "openid,profile,email"

session:
  secret: "dev-session-secret-key-32-chars-min"
  cookie_name: "compas-dev-session"
  max_age: 7200  # 2 hours for development

proxy:
  routes:
    - path: "/api/scl"
      upstream_url: "http://localhost:8082"
      strip_path: true
    - path: "/api/history"
      upstream_url: "http://localhost:8083"
      strip_path: true
    - path: "/"
      upstream_url: "http://localhost:3000"  # React dev server
      strip_path: false

security:
  allowed_origins:
    - "http://localhost:3000"
    - "http://localhost:8080"

logging:
  level: "debug"
  format: "text"
